package View;

import Controller.LivroController;
import Controller.EmprestimoController;
import Controller.UsuarioController;
import Model.LivroModel;
import Model.UsuarioModel;
import java.awt.Color;
import static java.awt.Transparency.TRANSLUCENT;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadastrarEmprestimo extends javax.swing.JFrame {

    Emprestimos emprestimo;

    public CadastrarEmprestimo() {
        initComponents();
        LocalDate date = LocalDate.now();
        DateTimeFormatter now = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String hoje = date.format(now);
        txtDataHoje.setText(hoje);
        listarUsuariosView();
        listarLivrosView();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        for (int i = 7; i < 15; i++) {
            LocalDate dataAtual = LocalDate.now().plusDays(i);
            String dia = dataAtual.format(formatter);
            jComboBox.addItem(dia);
        }
        
        JLabel background;
        ImageIcon img = new ImageIcon("Biblioteca_4.png");

        background = new JLabel("", img, JLabel.CENTER);
        background.setBounds(0, -75, 1024, 600);
        add(background);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelRelacaoUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaUsuarios = new javax.swing.JTable();
        btnPesquisarU = new javax.swing.JButton();
        txtPesquisarU = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PainelRelacaoBook = new javax.swing.JPanel();
        btnPesquisarL = new javax.swing.JButton();
        txtPesquisarL = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaLivros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        PainelInfoUser = new javax.swing.JPanel();
        lblID2 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        PainelInfoBook = new javax.swing.JPanel();
        lblID4 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblStatus4 = new javax.swing.JLabel();
        txtID2 = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        PainelInfoData = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        txtDataHoje = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelRelacaoUser.setBackground(new java.awt.Color(102, 102, 102, 70));
        PainelRelacaoUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Relação de Usuários"));
        PainelRelacaoUser.setPreferredSize(new java.awt.Dimension(475, 258));

        jTableListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableListaUsuariosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableListaUsuariosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableListaUsuariosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaUsuarios);

        btnPesquisarU.setText("PESQUISAR");
        btnPesquisarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUActionPerformed(evt);
            }
        });

        txtPesquisarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarUActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar nome:");

        javax.swing.GroupLayout PainelRelacaoUserLayout = new javax.swing.GroupLayout(PainelRelacaoUser);
        PainelRelacaoUser.setLayout(PainelRelacaoUserLayout);
        PainelRelacaoUserLayout.setHorizontalGroup(
            PainelRelacaoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRelacaoUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelRelacaoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelRelacaoUserLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarU, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarU)))
                .addGap(45, 45, 45))
        );
        PainelRelacaoUserLayout.setVerticalGroup(
            PainelRelacaoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelacaoUserLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(PainelRelacaoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisarU, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelRelacaoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesquisarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        PainelRelacaoBook.setBackground(new java.awt.Color(102, 102, 102, 70));
        PainelRelacaoBook.setBorder(javax.swing.BorderFactory.createTitledBorder("Relaão de Livros"));
        PainelRelacaoBook.setPreferredSize(new java.awt.Dimension(475, 262));

        btnPesquisarL.setText("PESQUISAR");
        btnPesquisarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLActionPerformed(evt);
            }
        });

        txtPesquisarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarLActionPerformed(evt);
            }
        });

        jTableListaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableListaLivrosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListaLivros);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisar título:");

        javax.swing.GroupLayout PainelRelacaoBookLayout = new javax.swing.GroupLayout(PainelRelacaoBook);
        PainelRelacaoBook.setLayout(PainelRelacaoBookLayout);
        PainelRelacaoBookLayout.setHorizontalGroup(
            PainelRelacaoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelacaoBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelRelacaoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRelacaoBookLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarL, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarL))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PainelRelacaoBookLayout.setVerticalGroup(
            PainelRelacaoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelacaoBookLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PainelRelacaoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarL)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelInfoUser.setBackground(new java.awt.Color(102, 102, 102, 70));
        PainelInfoUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Usuário"));

        lblID2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID2.setForeground(new java.awt.Color(255, 255, 255));
        lblID2.setText("ID:");

        lblNome2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(255, 255, 255));
        lblNome2.setText("Nome:");

        lblStatus2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus2.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus2.setText("CPF");

        txtID.setEditable(false);

        txtNome.setEditable(false);

        txtCPF.setEditable(false);

        javax.swing.GroupLayout PainelInfoUserLayout = new javax.swing.GroupLayout(PainelInfoUser);
        PainelInfoUser.setLayout(PainelInfoUserLayout);
        PainelInfoUserLayout.setHorizontalGroup(
            PainelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfoUserLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblID2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatus2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelInfoUserLayout.setVerticalGroup(
            PainelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfoUserLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PainelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInfoUserLayout.createSequentialGroup()
                        .addGroup(PainelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(PainelInfoUserLayout.createSequentialGroup()
                        .addGroup(PainelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNome2)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblStatus2)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        PainelInfoBook.setBackground(new java.awt.Color(102, 102, 102, 70));
        PainelInfoBook.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Livro"));

        lblID4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID4.setForeground(new java.awt.Color(255, 255, 255));
        lblID4.setText("ID:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Titulo:");

        lblStatus4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus4.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus4.setText("Genero");

        txtID2.setEditable(false);

        txtTitulo.setEditable(false);

        txtAutor.setEditable(false);

        javax.swing.GroupLayout PainelInfoBookLayout = new javax.swing.GroupLayout(PainelInfoBook);
        PainelInfoBook.setLayout(PainelInfoBookLayout);
        PainelInfoBookLayout.setHorizontalGroup(
            PainelInfoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfoBookLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblID4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatus4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelInfoBookLayout.setVerticalGroup(
            PainelInfoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfoBookLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PainelInfoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInfoBookLayout.createSequentialGroup()
                        .addGroup(PainelInfoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID4)
                            .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(PainelInfoBookLayout.createSequentialGroup()
                        .addGroup(PainelInfoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelInfoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTitulo)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelInfoBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblStatus4)
                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE))))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        PainelInfoData.setBackground(new java.awt.Color(102, 102, 102, 70));
        PainelInfoData.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da devolução"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data de Devolução");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data da Retirada:");

        try {
            txtDataHoje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**/**/****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataHojeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInfoDataLayout = new javax.swing.GroupLayout(PainelInfoData);
        PainelInfoData.setLayout(PainelInfoDataLayout);
        PainelInfoDataLayout.setHorizontalGroup(
            PainelInfoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfoDataLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        PainelInfoDataLayout.setVerticalGroup(
            PainelInfoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInfoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelInfoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnSalvar)
                        .addGap(12, 12, 12)
                        .addComponent(PainelInfoBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelRelacaoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelRelacaoBook, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelInfoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PainelInfoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PainelInfoBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSalvar)))
                .addGap(18, 18, 18)
                .addComponent(PainelInfoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelRelacaoBook, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(PainelRelacaoUser, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListaUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaUsuariosKeyPressed
        String nome = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 1).toString();

        String status = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 2).toString();

        String idAux = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 0).toString();

        txtID.setText(idAux);
        txtNome.setText(nome);
        txtCPF.setText(status);
    }//GEN-LAST:event_jTableListaUsuariosKeyPressed

    private void jTableListaUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaUsuariosKeyReleased
        String nome = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 1).toString();

        String status = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 2).toString();

        String idAux = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 0).toString();

        txtID.setText(idAux);
        txtNome.setText(nome);
        txtCPF.setText(status);
    }//GEN-LAST:event_jTableListaUsuariosKeyReleased

    private void jTableListaUsuariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaUsuariosKeyTyped
        String nome = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 1).toString();

        String status = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 2).toString();

        String idAux = jTableListaUsuarios.getModel().
                getValueAt(jTableListaUsuarios.getSelectedRow(), 0).toString();

        txtID.setText(idAux);
        txtNome.setText(nome);
        txtCPF.setText(status);
    }//GEN-LAST:event_jTableListaUsuariosKeyTyped

    private void btnPesquisarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUActionPerformed
        String itemPesquisa = txtPesquisarU.getText();

        try {

            DefaultTableModel dtm = (DefaultTableModel) jTableListaUsuarios.getModel();
            dtm.setRowCount(0);
            UsuarioController UsuarioControler = new UsuarioController();
            ArrayList<UsuarioModel> listaUsuarios
                    = UsuarioControler.buscarUsuariosController(itemPesquisa);

            Iterator<UsuarioModel> iterator = listaUsuarios.iterator();

            while (iterator.hasNext()) {
                UsuarioModel Usuario = iterator.next();
                dtm.addRow(new Object[]{
                    Usuario.getId(),
                    Usuario.getNome(),
                    Usuario.getCpf(),
                    Usuario.getEmail(),
                    Usuario.getEndereco(),
                    Usuario.getDatanascimento(),
                    Usuario.getStatus(),});
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPesquisarUActionPerformed

    private void txtPesquisarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarUActionPerformed

    private void btnPesquisarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarLActionPerformed
                String itemPesquisa = txtPesquisarL.getText();

        try {

            DefaultTableModel dtm = (DefaultTableModel) jTableListaLivros.getModel();
            dtm.setRowCount(0);
            LivroController LivroControler = new LivroController();
            ArrayList<LivroModel> listaLivros
                    = LivroControler.buscarLivrosController(itemPesquisa);

            Iterator<LivroModel> iterator = listaLivros.iterator();

            while (iterator.hasNext()) {
                LivroModel Livro = iterator.next();
                dtm.addRow(new Object[]{
                    Livro.getId(),
                    Livro.getTitulo(),
                    Livro.getGenero(),});
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPesquisarLActionPerformed

    private void txtPesquisarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarLActionPerformed
    }//GEN-LAST:event_txtPesquisarLActionPerformed

    private void jTableListaLivrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaLivrosKeyPressed
        String idAux = jTableListaLivros.getModel().
                getValueAt(jTableListaLivros.getSelectedRow(), 0).toString();

        String titulo = jTableListaLivros.getModel().
                getValueAt(jTableListaLivros.getSelectedRow(), 1).toString();

        String autor = jTableListaLivros.getModel().
                getValueAt(jTableListaLivros.getSelectedRow(), 2).toString();

        txtID2.setText(idAux);
        txtTitulo.setText(titulo);
        txtAutor.setText(autor);
    }//GEN-LAST:event_jTableListaLivrosKeyPressed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
            String id = txtID.getText();
            String id2 = txtID2.getText();
        if (!"".equals(id) && !"".equals(id2)) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            Integer idUser = Integer.valueOf(id);

            Integer idBook = Integer.valueOf(id2);

            String dataLocacao = txtDataHoje.getText();
            LocalDate dateLocacao = LocalDate.parse(dataLocacao, formatter);

            String dataDevolucao = (String) jComboBox.getSelectedItem();
            System.out.println(dataDevolucao);
            LocalDate dateDevolucao = LocalDate.parse(dataDevolucao, formatter);

            String status = "Ativo";

            long daysBetween = dateDevolucao.toEpochDay() - dateLocacao.toEpochDay();

            int dias = Long.valueOf(daysBetween).intValue();

            EmprestimoController novoEmprestimo = new EmprestimoController();
            novoEmprestimo.cadastrarEmprestimo(idUser, idBook, dataLocacao, dataDevolucao, status);

            txtID.setText("");
            txtNome.setText("");
            txtCPF.setText("");
            txtID2.setText("");
            txtTitulo.setText("");
            txtAutor.setText("");

            LivroController ajustarStatus = new LivroController();
            ajustarStatus.alterarStatus(idBook, "Emprestado");

            this.dispose();

            this.emprestimo.listarEmprestimosView();
        } else {
            JOptionPane.showMessageDialog(null, "Precisa selecionar um livro e um usuario para cadastrar um emprestimo");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtDataHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataHojeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataHojeActionPerformed

    void listarUsuariosView() {

        try {
            DefaultTableModel dtm = (DefaultTableModel) jTableListaUsuarios.getModel();
            dtm.setRowCount(0);
            UsuarioController UsuarioControler = new UsuarioController();
            ArrayList<UsuarioModel> listaUsuarios = UsuarioControler.listarUsuariosController();

            Iterator<UsuarioModel> iterator = listaUsuarios.iterator();

            while (iterator.hasNext()) {
                UsuarioModel Usuario = iterator.next();
                if (!"Bloqueado".equals(Usuario.getStatus())) {
                    dtm.addRow(new Object[]{
                        Usuario.getId(),
                        Usuario.getNome(),
                        Usuario.getCpf(),});
                }
            }

        } catch (Exception e) {
        }

    }

    void listarLivrosView() {

        try {
            DefaultTableModel dtm = (DefaultTableModel) jTableListaLivros.getModel();
            dtm.setRowCount(0);
            LivroController livroControler = new LivroController();
            ArrayList<LivroModel> listaLivros = livroControler.listarLivrosController();

            Iterator<LivroModel> iterator = listaLivros.iterator();

            while (iterator.hasNext()) {
                LivroModel livro = iterator.next();
                if (!"Emprestado".equals(livro.getStatus())) {
                    dtm.addRow(new Object[]{
                        livro.getId(),
                        livro.getTitulo(),
                        livro.getGenero()});
                }
            }

        } catch (Exception e) {
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelInfoBook;
    private javax.swing.JPanel PainelInfoData;
    private javax.swing.JPanel PainelInfoUser;
    private javax.swing.JPanel PainelRelacaoBook;
    public javax.swing.JPanel PainelRelacaoUser;
    private javax.swing.JButton btnPesquisarL;
    private javax.swing.JButton btnPesquisarU;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListaLivros;
    private javax.swing.JTable jTableListaUsuarios;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblID4;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel lblStatus4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JFormattedTextField txtDataHoje;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisarL;
    private javax.swing.JTextField txtPesquisarU;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
